@php($showWilayah = $showWilayah ?? true)
<div class="grid gap-5 sm:grid-cols-2">
    <div><label class="mb-2 block text-sm font-semibold">NIK</label><input name="nik" value="{{ old('nik',$citizen->nik) }}" maxlength="16" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Nomor Kartu Keluarga</label><input name="family_card_number" value="{{ old('family_card_number',$citizen->family_card_number) }}" maxlength="16" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Nama lengkap</label><input name="name" value="{{ old('name',$citizen->name) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Jenis kelamin</label><select name="gender" required class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="L" @selected(old('gender',$citizen->gender)==='L')>Laki-laki</option><option value="P" @selected(old('gender',$citizen->gender)==='P')>Perempuan</option></select></div>
    <div><label class="mb-2 block text-sm font-semibold">Tanggal lahir</label><input type="date" name="birth_date" value="{{ old('birth_date',optional($citizen->birth_date)->format('Y-m-d')) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Nomor telepon</label><input name="phone" value="{{ old('phone',$citizen->phone) }}" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold">Alamat</label><textarea name="address" rows="3" required class="w-full rounded-xl border border-slate-300 px-4 py-3">{{ old('address',$citizen->address) }}</textarea></div>
    <div><label class="mb-2 block text-sm font-semibold">RT</label><input name="rt" value="{{ old('rt',$citizen->rt) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">RW</label><input name="rw" value="{{ old('rw',$citizen->rw) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    @if($showWilayah)<div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold">Kode/nama wilayah</label><input name="wilayah" value="{{ old('wilayah',$citizen->wilayah) }}" placeholder="Contoh: RT 001 / RW 002" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>@endif
    <div><label class="mb-2 block text-sm font-semibold">Desa/Kelurahan</label><input name="village" value="{{ old('village',$citizen->village) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Kecamatan</label><input name="district" value="{{ old('district',$citizen->district) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Penghasilan per bulan</label><input type="number" min="0" name="income" value="{{ old('income',$citizen->income) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Jumlah tanggungan</label><input type="number" min="0" max="30" name="dependents" value="{{ old('dependents',$citizen->dependents ?? 0) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div>
    <div><label class="mb-2 block text-sm font-semibold">Kondisi rumah</label><select name="house_condition" required class="w-full rounded-xl border border-slate-300 px-4 py-3">@foreach(['sangat_tidak_layak'=>'Sangat tidak layak','tidak_layak'=>'Tidak layak','cukup'=>'Cukup','layak'=>'Layak'] as $value=>$label)<option value="{{ $value }}" @selected(old('house_condition',$citizen->house_condition ?? 'cukup')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div><label class="mb-2 block text-sm font-semibold">Ada lansia dalam keluarga?</label><select name="has_elderly" class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="1" @selected((string)old('has_elderly',(int)$citizen->has_elderly)==='1')>Ya</option><option value="0" @selected((string)old('has_elderly',(int)$citizen->has_elderly)==='0')>Tidak</option></select></div>
    <div><label class="mb-2 block text-sm font-semibold">Ada penyandang disabilitas?</label><select name="has_disability" class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="1" @selected((string)old('has_disability',(int)$citizen->has_disability)==='1')>Ya</option><option value="0" @selected((string)old('has_disability',(int)$citizen->has_disability)==='0')>Tidak</option></select></div>
    <div><label class="mb-2 block text-sm font-semibold">Orang tua tunggal?</label><select name="is_single_parent" class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="1" @selected((string)old('is_single_parent',(int)$citizen->is_single_parent)==='1')>Ya</option><option value="0" @selected((string)old('is_single_parent',(int)$citizen->is_single_parent)==='0')>Tidak</option></select></div>
</div>
