@extends('layouts.app')
@section('title', $program->exists ? 'Edit Program' : 'Tambah Program')
@section('page-title', $program->exists ? 'Edit Program Bantuan' : 'Tambah Program Bantuan')
@section('content')
<form action="{{ $program->exists ? route('admin.programs.update',$program) : route('admin.programs.store') }}" method="POST" class="max-w-4xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">@csrf @if($program->exists) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-semibold">Kode program</label><input name="code" value="{{ old('code',$program->code) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Nama program</label><input name="name" value="{{ old('name',$program->name) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold">Deskripsi</label><textarea name="description" rows="4" class="w-full rounded-xl border border-slate-300 px-4 py-3">{{ old('description',$program->description) }}</textarea></div><div><label class="mb-2 block text-sm font-semibold">Kuota penerima</label><input type="number" min="1" name="quota" value="{{ old('quota',$program->quota) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Anggaran</label><input type="number" min="0" name="budget" value="{{ old('budget',$program->budget) }}" required class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Tanggal mulai</label><input type="date" name="start_date" value="{{ old('start_date',optional($program->start_date)->format('Y-m-d')) }}" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Tanggal selesai</label><input type="date" name="end_date" value="{{ old('end_date',optional($program->end_date)->format('Y-m-d')) }}" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><div><label class="mb-2 block text-sm font-semibold">Status</label><select name="status" class="w-full rounded-xl border border-slate-300 px-4 py-3">@foreach(['draft'=>'Draft','active'=>'Aktif','closed'=>'Ditutup'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$program->status ?? 'draft')===$value)>{{ $label }}</option>@endforeach</select></div></div>
<div class="mt-7 flex gap-3"><button class="rounded-xl bg-emerald-800 px-5 py-3 font-semibold text-white">Simpan</button><a href="{{ route('admin.programs.index') }}" class="rounded-xl border border-slate-300 px-5 py-3 font-semibold">Batal</a></div>
</form>
@endsection
