@extends('layouts.app')
@section('title', 'Program Bantuan')
@section('page-title', 'Program Bantuan')
@section('content')
<div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold">Daftar Program</h2><p class="text-sm text-slate-500">Atur periode, kuota, anggaran, dan status program bantuan.</p></div><a href="{{ route('admin.programs.create') }}" class="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-semibold text-white">Tambah Program</a></div>
<div class="grid gap-4 lg:grid-cols-2">
@forelse($programs as $program)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wider text-emerald-700">{{ $program->code }}</p><h3 class="mt-1 text-lg font-bold">{{ $program->name }}</h3></div><x-status-badge :status="$program->status" /></div><p class="mt-3 text-sm leading-6 text-slate-600">{{ $program->description ?: 'Tidak ada deskripsi.' }}</p><div class="mt-5 grid grid-cols-3 gap-3 rounded-xl bg-slate-50 p-4 text-center"><div><p class="text-xs text-slate-500">Kuota</p><p class="font-bold">{{ $program->quota }}</p></div><div><p class="text-xs text-slate-500">Penerima</p><p class="font-bold">{{ $program->recipients_count }}</p></div><div><p class="text-xs text-slate-500">Anggaran</p><p class="font-bold">Rp{{ number_format($program->budget,0,',','.') }}</p></div></div><div class="mt-5 flex gap-2"><a href="{{ route('admin.programs.edit',$program) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">Edit</a>@if($program->recipients_count===0)<form method="POST" action="{{ route('admin.programs.destroy',$program) }}" onsubmit="return confirm('Hapus program ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-3 py-2 text-sm text-rose-700">Hapus</button></form>@endif</div></div>@empty<div class="lg:col-span-2"><x-empty-state message="Belum ada program bantuan." /></div>@endforelse
</div><div class="mt-5">{{ $programs->links() }}</div>
@endsection
