@extends('layouts.app')
@section('title', 'Hasil Verifikasi')
@section('page-title', 'Verifikasi Warga')
@section('content')
<div class="grid gap-6 xl:grid-cols-[380px_1fr]">
<section class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-bold">Tugaskan Surveyor</h2><p class="mt-1 text-sm text-slate-500">Pilih warga yang masih berstatus pending.</p><form action="{{ route('admin.verifications.store') }}" method="POST" class="mt-5 space-y-4">@csrf<div><label class="mb-2 block text-sm font-semibold">Warga</label><select name="citizen_id" required class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="">Pilih warga</option>@foreach($pendingCitizens as $citizen)<option value="{{ $citizen->id }}">{{ $citizen->name }} — {{ $citizen->wilayah }}</option>@endforeach</select></div><div><label class="mb-2 block text-sm font-semibold">Surveyor</label><select name="surveyor_id" required class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="">Pilih surveyor</option>@foreach($surveyors as $surveyor)<option value="{{ $surveyor->id }}">{{ $surveyor->name }}</option>@endforeach</select></div><div><label class="mb-2 block text-sm font-semibold">Jadwal survei</label><input type="datetime-local" name="scheduled_at" class="w-full rounded-xl border border-slate-300 px-4 py-3"></div><button class="w-full rounded-xl bg-emerald-800 px-4 py-3 font-semibold text-white">Buat Tugas Survei</button></form></section>
<section><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold">Daftar Verifikasi</h2><p class="text-sm text-slate-500">Pantau penugasan dan hasil survei lapangan.</p></div><form><select name="status" onchange="this.form.submit()" class="rounded-xl border border-slate-300 px-4 py-2.5"><option value="">Semua status</option>@foreach(['assigned','verified','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></form></div><div class="space-y-3">@forelse($surveys as $survey)<a href="{{ route('admin.verifications.show',$survey) }}" class="block rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-300"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold">{{ $survey->citizen->name }}</h3><p class="mt-1 text-sm text-slate-500">{{ $survey->citizen->wilayah }} • Surveyor: {{ $survey->surveyor->name }}</p><p class="mt-1 text-xs text-slate-400">Jadwal {{ optional($survey->scheduled_at)->format('d M Y H:i') ?? 'belum ditentukan' }}</p></div><div class="text-right"><x-status-badge :status="$survey->status" />@if($survey->priority_score!==null)<p class="mt-2 text-sm font-bold text-emerald-800">Skor {{ $survey->priority_score }}</p>@endif</div></div></a>@empty<x-empty-state message="Belum ada proses verifikasi." />@endforelse</div><div class="mt-5">{{ $surveys->links() }}</div></section>
</div>
@endsection
