@extends('layouts.app')
@section('title', 'Data Warga')
@section('page-title', 'Kelola Data Warga')
@section('content')
<div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold">Seluruh Data Warga</h2><p class="text-sm text-slate-500">Admin dapat melihat, menambah, mengubah, dan menghapus seluruh data.</p></div><a href="{{ route('admin.citizens.create') }}" class="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-semibold text-white">Tambah Warga</a></div>
<form class="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 lg:grid-cols-[1fr_180px_220px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Cari nama atau NIK..." class="rounded-xl border border-slate-300 px-4 py-2.5"><select name="status" class="rounded-xl border border-slate-300 px-4 py-2.5"><option value="">Semua status</option>@foreach(['pending','assigned','verified','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><select name="wilayah" class="rounded-xl border border-slate-300 px-4 py-2.5"><option value="">Semua wilayah</option>@foreach($wilayahList as $wilayah)<option @selected(request('wilayah')===$wilayah)>{{ $wilayah }}</option>@endforeach</select><button class="rounded-xl border border-slate-300 px-4 py-2.5 font-semibold">Filter</button></form>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Warga</th><th class="px-5 py-3">Wilayah</th><th class="px-5 py-3">Ekonomi</th><th class="px-5 py-3">Verifikasi</th><th class="px-5 py-3">Skor</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($citizens as $citizen)<tr><td class="px-5 py-4"><p class="font-semibold">{{ $citizen->name }}</p><p class="text-xs text-slate-500">NIK {{ $citizen->nik }}</p></td><td class="px-5 py-4">{{ $citizen->wilayah }}<p class="text-xs text-slate-500">{{ $citizen->village }}</p></td><td class="px-5 py-4">Rp{{ number_format($citizen->income,0,',','.') }}<p class="text-xs text-slate-500">{{ $citizen->dependents }} tanggungan</p></td><td class="px-5 py-4"><x-status-badge :status="$citizen->verification_status" /></td><td class="px-5 py-4 font-bold">{{ $citizen->latestSurvey?->priority_score ?? '—' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.citizens.edit',$citizen) }}" class="rounded-lg border border-slate-300 px-3 py-2">Edit</a><form action="{{ route('admin.citizens.destroy',$citizen) }}" method="POST" onsubmit="return confirm('Hapus data warga ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-3 py-2 text-rose-700">Hapus</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">Data warga tidak ditemukan.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-5">{{ $citizens->links() }}</div>
@endsection
