@extends('layouts.app')
@section('title', 'Ranking Prioritas')
@section('page-title', 'Ranking Prioritas Penerima')
@section('content')
<div class="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-xl font-bold">Pemeringkatan Otomatis</h2><p class="mt-1 max-w-3xl text-sm text-slate-500">Skor dihitung dari penghasilan, kondisi rumah, tanggungan, lansia, disabilitas, dan status orang tua tunggal. Keputusan akhir tetap dilakukan admin.</p></div><form class="flex gap-2"><input name="wilayah" value="{{ request('wilayah') }}" placeholder="Filter wilayah..." class="rounded-xl border border-slate-300 px-4 py-2.5"><button class="rounded-xl border border-slate-300 px-4 py-2.5 font-semibold">Filter</button></form></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-emerald-950 text-left text-xs uppercase tracking-wider text-emerald-100"><tr><th class="px-5 py-4">Ranking</th><th class="px-5 py-4">Warga</th><th class="px-5 py-4">Wilayah</th><th class="px-5 py-4">Penghasilan</th><th class="px-5 py-4">Tanggungan</th><th class="px-5 py-4">Kondisi Rumah</th><th class="px-5 py-4 text-center">Skor</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($rankings as $survey)<tr class="{{ $loop->iteration <= 3 && $rankings->currentPage()===1 ? 'bg-amber-50' : '' }}"><td class="px-5 py-4"><span class="grid h-9 w-9 place-items-center rounded-full bg-slate-900 font-bold text-white">{{ ($rankings->currentPage()-1)*$rankings->perPage()+$loop->iteration }}</span></td><td class="px-5 py-4"><p class="font-bold">{{ $survey->citizen->name }}</p><p class="text-xs text-slate-500">{{ $survey->citizen->nik }}</p></td><td class="px-5 py-4">{{ $survey->citizen->wilayah }}</td><td class="px-5 py-4">Rp{{ number_format($survey->verified_income,0,',','.') }}</td><td class="px-5 py-4">{{ $survey->verified_dependents }} orang</td><td class="px-5 py-4 capitalize">{{ str_replace('_',' ',$survey->verified_house_condition) }}</td><td class="px-5 py-4 text-center"><span class="inline-grid h-12 w-12 place-items-center rounded-xl bg-emerald-100 text-lg font-black text-emerald-900">{{ $survey->priority_score }}</span></td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">Belum ada warga terverifikasi untuk diranking.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-5">{{ $rankings->links() }}</div>
@endsection
